def setup_captain_nested_chats(project_description, captain):
    """
    Sets up the Captain agent to handle nested chats for project definition and refinement.

    Args:
        project_description (str): The initial idea or description of the project.
        captain (CaptainAgent): The Captain agent managing the nested chat workflow.

    Returns:
        CaptainAgent: The Captain agent orchestrating the nested chat workflow.
    """

    # Create agents with detailed system messages
    generator_agent = captain.create_agent(
        "GeneratorAgent",
        """
        You are responsible for generating system prompts for project tasks. 
        Ensure prompts are clear, actionable, and structured for efficiency.
        """
    )
    critic_agent = captain.create_agent(
        "CriticAgent",
        """
        You evaluate the system prompts generated by the GeneratorAgent. 
        Focus on clarity, actionability, and structure. 
        Provide constructive feedback and a score from 1 to 100. 
        If the score is 95 or above, append 'terminate' to your response.
        """
    )
    user_proxy_agent = captain.create_agent(
        "UserProxyAgent",
        """
        You orchestrate the workflow between GeneratorAgent and CriticAgent. 
        Ensure smooth transitions and proper task execution. 
        Provide the final output after refinement.
        """
    )

    # Define the nested chat workflow
    nested_chats = [
        {
            "recipient": generator_agent,
            "message": f"""
            Develop a detailed project description for the following task: 
            {project_description}. 
            Ensure the description is structured, clear, and actionable. 
            Respond ONLY with the project description.
            """,
            "summary_method": "last_msg",
            "max_turns": 2,
        },
        {
            "recipient": critic_agent,
            "message": """
            Review the project description provided by GeneratorAgent. 
            Focus on clarity, actionability, and structure. 
            Provide a score from 1 to 100. 
            If the score is 95 or higher, respond ONLY with your feedback and score.
            """,
            "summary_method": "last_msg",
            "max_turns": 2,
        },
        {
            "recipient": generator_agent,
            "message": """
            Respond ONLY with the updated project description.
            """,
            "summary_method": "last_msg",
            "max_turns": 1,
        },
    ]

    # Register nested chats
    generator_agent.register_nested_chats(
        chat_queue=nested_chats,
        trigger=user_proxy_agent,
        
    )

    return captain


def execute_project_definition(project_description, captain):
    """
    Executes the nested chat workflow for project definition and refinement.

    Args:
        project_description (str): The initial idea or description of the project.
        captain (CaptainAgent): The Captain agent managing the workflow.

    Returns:
        str: Final refined project definition.
    """

    # Setup nested chats with Captain
    captain = setup_captain_nested_chats(project_description, captain)

    # Start the workflow
    trigger_message = captain.agents["UserProxyAgent"].initiate_chat(
        recipient=captain.agents["GeneratorAgent"],
        message={"content": f"Start project refinement for: {project_description}."},
        max_turns=1,
    )

    # Extract the final refined output
    final_project_plan = trigger_message.chat_history[-1]["content"]
    return final_project_plan
