def setup_captain_nested_chats( project_description,captain):
    """
    Sets up the Captain agent to handle nested chats for project definition and refinement.

    Args:
        llm_config (dict): Configuration for the language model.
        project_description (str): The initial idea or description of the project.

    Returns:
        CaptainAgent: The Captain agent orchestrating the nested chat workflow.
    """
    

    # Create agents with detailed system messages
    generator_agent = captain.create_agent_assistant(
        "GeneratorAgent",
        "You are responsible for generating system prompts for project tasks. Ensure prompts are clear, actionable, and structured for efficiency.",
    )
    critic_agent = captain.create_agent_assistant(
        "CriticAgent",
        "You evaluate the system prompts generated by the GeneratorAgent. Focus on clarity, actionability, and structure. Provide constructive feedback and a score from 1 to 100. If the score is 95 or above, append 'terminate' to your response.",
    )
    user_proxy_agent = captain.create_agent_user_proxy(
        "UserProxyAgent",
        "You orchestrate the workflow between GeneratorAgent and CriticAgent. Ensure smooth transitions and proper task execution. Provide the final output after refinement.",
    )
    struted_output_agent = captain.create_agent_assistant(
    agent_name="StructuredOutputAgent",
    system_message=(
        "You are a structured output agent tasked with producing well-organized, "
        "hierarchical outputs from complex project descriptions. Your responsibilities include:\n\n"
        "1. Breaking down the input into distinct sections and subsections.\n"
        "2. Structuring the output in a clear, numbered, and hierarchical format.\n"
        "3. Ensuring each section is actionable, concise, and complete.\n"
        "4. Adding bullet points or numbered lists where applicable.\n"
        "5. Highlighting areas for improvement or adding clarifications if necessary.\n"
        "6. Following this structure for all outputs:\n"
        "   ------------------------\n"
        "   ## 1. Section Title\n"
        "   ------------------------\n"
        "   ### 1.1 Subsection Title\n"
        "   - **1**: Key point.\n"
        "   - **2**: Key point.\n"
        "   ------------------------\n\n"
        "If the input lacks clarity, infer logical sections based on context. Respond only with "
        "the structured output in the required format."
    )
)


    # Define the nested chat workflow
    nested_chats = [
        {
            "recipient": generator_agent,
            "message": f"Develop a detailed project description for the following task: {project_description}. Ensure the description is structured,(Headliners inform of x =number),Subpoints x.x clear, and actionable. Respond ONLY with the project description.",
            "summary_method": "last_msg",
            "max_turns": 1,
        },
        {
            "recipient": critic_agent,
            "message": """Review the project description provided by GeneratorAgent. 
                          Focus on clarity, actionability, and structure. 
                          Provide a score from 1 to 100. If the score is 95 or higher. 
                          Respond ONLY with your feedback and score.""",
            "summary_method": "last_msg",
            "max_turns": 1,
        },
        {
            "recipient": generator_agent,
            "message": "Update the project description based on the feedback from Respond ONLY with the updated project description..",
            "summary_method": "reflection_with_llm",	
            "max_turns": 1,
        },
        {
            "recipient": struted_output_agent,
            "message": """Respond ONLY with the updated project description.""",
            "summary_method": "last_msg",	
            "max_turns": 1,
        },
        

    ]


    # Register nested chats
    generator_agent.register_nested_chats(
        chat_queue=nested_chats,
        trigger=user_proxy_agent,
    )

    return captain



def execute_project_definition(project_description,captain ):
    """
    Executes the nested chat workflow for project definition and refinement.

    Args:
        project_description (str): The initial idea or description of the project.
        llm_config (dict): Configuration for the language model.

    Returns:
        str: Final refined project definition.
    """
    captain = setup_captain_nested_chats( project_description,captain)

    # Start the workflow
    trigger_message = captain.agents["UserProxyAgent"].initiate_chat(
        recipient=captain.agents["GeneratorAgent"],
        message={"content": f"Start project refinement for: {project_description}."},
        max_turns=1,
    )

    # Return the final refined output
    final_project_plan = trigger_message.chat_history[-1]["content"]
    return final_project_plan

def execute_project_definition_structured(project_description,captain):
    """
    Executes the nested chat workflow for project definition and refinement.

    Args:
        project_description (str): The initial idea or description of the project.
        llm_config (dict): Configuration for the language model.

    Returns:
        str: Final refined project definition.
    """
    captain = setup_captain_nested_chats(project_description,captain)

    # Start the workflow
    trigger_message = captain.agents["UserProxyAgent"].initiate_chat(
        recipient=captain.agents["GeneratorAgent"],
        message={"content": f"Start project refinement for: {project_description}."},
        max_turns=1,
    )

    # Return the final refined output
    final_project_plan = trigger_message.chat_history[-1]["content"]
    return final_project_plan





