"""Break a refined project description into sections/subsections/tasks/assignments."""
from .base import AgentRoleSpec, NestedChatWorkflow, WorkflowStep
from .registry import register_workflow

_CARRYOVER = (
    "ALLWAYS INCLUDE the PROJECT DESCRIPTION:\n {project_description}\n IN THE SORT OUT WHAT NOT IS "
    "IN THE CONTEXT OF PROGRAMMING IDEAS GATHERING AND DESGINING PROZESSES ARE GOOD FOR ORGANZIE "
    "TASKS{project_description}"
)


@register_workflow("project_structuring")
def build() -> NestedChatWorkflow:
    return NestedChatWorkflow(
        name="project_structuring",
        roles=[
            AgentRoleSpec(
                "generator",
                "You are responsible for breaking down the input into a structured dictionary with "
                "sections, subsections, and tasks. Ensure that all information is logically divided "
                "and actionable. Follow this format:\n"
                "{{\n"
                "  'overview': ['List of all major sections'],\n"
                "  'sections': {{\n"
                "    'Section Title': {{\n"
                "      'subsections': {{\n"
                "        'Subsection Title': {{\n"
                "          'tasks': ['Task 1', 'Task 2'],\n"
                "          'assignments': {{\n"
                "            'teams': ['Team 1'],\n"
                "            'individuals': ['Individual 1']\n"
                "          }}\n"
                "        }}\n"
                "      }},\n"
                "      'assignments': {{\n"
                "        'teams': ['Team 1'],\n"
                "        'individuals': ['Individual 1']\n"
                "      }}\n"
                "    }}\n"
                "  }},\n"
                "  'tasks': ['Flat list of all tasks'],\n"
                "  'context_teams': ['List of collaborating teams']\n"
                "}}\n",
            ),
            AgentRoleSpec(
                "critic",
                "You review and refine the structured dictionary generated by GeneratorAgent. "
                "Focus on completeness, clarity, and logical organization. Ensure tasks and "
                "assignments are actionable and logically grouped. Provide constructive feedback "
                "and suggest improvements where necessary.",
            ),
            AgentRoleSpec(
                "structured_output",
                "You finalize the structured dictionary into a clean, hierarchical format. "
                "Ensure it is formatted as per the requested structure and contains all information "
                "clearly organized.",
            ),
            AgentRoleSpec(
                "user_proxy",
                "You manage the workflow between GeneratorAgent, CriticAgent, and StructuredOutputAgent. "
                "Ensure smooth transitions and proper task execution, and provide the final structured output.",
                kind="user_proxy",
            ),
        ],
        steps=[
            WorkflowStep(
                recipient_role="generator",
                message=(
                    "Analyze the project description: {project_description}. "
                    "Break it down into a structured dictionary with sections, subsections, tasks, and assignments."
                ),
                max_turns=2,
                carryover=_CARRYOVER,
            ),
            WorkflowStep(
                recipient_role="critic",
                message=(
                    "Review the structured dictionary generated by GeneratorAgent. Ensure it is complete, "
                    "actionable, and logically organized. Provide feedback and suggest refinements if necessary."
                ),
                summary_method="reflection_with_llm",
                max_turns=1,
                carryover=_CARRYOVER,
            ),
            WorkflowStep(
                recipient_role="generator",
                message=(
                    "Refine the structured dictionary based on feedback from CriticAgent. "
                    "Ensure all suggestions are incorporated. Respond ONLY with the refined dictionary."
                ),
                max_turns=1,
                carryover=_CARRYOVER,
            ),
            WorkflowStep(
                recipient_role="structured_output",
                message=(
                    "Finalize the refined structured dictionary into a clean, hierarchical format. "
                    "Ensure it adheres to the requested structure with sections, subsections, tasks, and "
                    "assignments. Respond ONLY with the final structured dictionary."
                ),
                max_turns=1,
                carryover=_CARRYOVER,
            ),
        ],
        entry_role="generator",
        trigger_role="user_proxy",
        kickoff_message="Start processing the project description into a structured dictionary.",
    )
