"""Refine a raw project idea into a clear, structured description."""
from .base import AgentRoleSpec, NestedChatWorkflow, WorkflowStep
from .registry import register_workflow


@register_workflow("project_definition")
def build() -> NestedChatWorkflow:
    return NestedChatWorkflow(
        name="project_definition",
        roles=[
            AgentRoleSpec(
                "generator",
                "You are responsible for generating system prompts for project tasks. "
                "Ensure prompts are clear, actionable, and structured for efficiency.",
            ),
            AgentRoleSpec(
                "critic",
                "You evaluate the system prompts generated by the GeneratorAgent. Focus on clarity, "
                "actionability, and structure. Provide constructive feedback and a score from 1 to 100. "
                "If the score is 95 or above, append 'terminate' to your response.",
            ),
            AgentRoleSpec(
                "structured_output",
                "You are a structured output agent tasked with producing well-organized, hierarchical "
                "outputs from complex project descriptions. Your responsibilities include:\n\n"
                "1. Breaking down the input into distinct sections and subsections.\n"
                "2. Structuring the output in a clear, numbered, and hierarchical format.\n"
                "3. Ensuring each section is actionable, concise, and complete.\n"
                "4. Adding bullet points or numbered lists where applicable.\n"
                "5. Highlighting areas for improvement or adding clarifications if necessary.\n"
                "6. Following this structure for all outputs:\n"
                "   ------------------------\n"
                "   ## 1. Section Title\n"
                "   ------------------------\n"
                "   ### 1.1 Subsection Title\n"
                "   - **1**: Key point.\n"
                "   - **2**: Key point.\n"
                "   ------------------------\n\n"
                "If the input lacks clarity, infer logical sections based on context. Respond only with "
                "the structured output in the required format.",
            ),
            AgentRoleSpec(
                "user_proxy",
                "You orchestrate the workflow between GeneratorAgent and CriticAgent. Ensure smooth "
                "transitions and proper task execution. Provide the final output after refinement.",
                kind="user_proxy",
            ),
        ],
        steps=[
            WorkflowStep(
                recipient_role="generator",
                message=(
                    "Develop a detailed project description for the following task: {project_description}. "
                    "Ensure the description is structured,(Headliners inform of x =number),Subpoints x.x "
                    "clear, and actionable. Respond ONLY with the project description."
                ),
                max_turns=1,
            ),
            WorkflowStep(
                recipient_role="critic",
                message=(
                    "Review the project description provided by GeneratorAgent. "
                    "Focus on clarity, actionability, and structure. "
                    "Provide a score from 1 to 100. If the score is 95 or higher. "
                    "Respond ONLY with your feedback and score."
                ),
                max_turns=1,
            ),
            WorkflowStep(
                recipient_role="generator",
                message="Update the project description based on the feedback from Respond ONLY with the updated project description..",
                summary_method="reflection_with_llm",
                max_turns=1,
            ),
            WorkflowStep(
                recipient_role="structured_output",
                message="Respond ONLY with the updated project description.",
                max_turns=1,
            ),
        ],
        entry_role="generator",
        trigger_role="user_proxy",
        kickoff_message="Start project refinement for: {project_description}.",
    )
